app = "frame-cap-tool"
primary_region = "ord" # Chicago


[http_service]
internal_port = 80
force_https = true


# Max savings: fully stop idle Machines, wake on request
auto_stop_machines = "stop" # use "suspend" for faster wakes (slightly higher idle storage use)
auto_start_machines = true
min_machines_running = 0 # scale to zero in primary region too


# With ~20 users, this will wake an extra Machine only if you pre-provision one
[http_service.concurrency]
type = "requests"
soft_limit = 20
hard_limit = 40


# Smallest preset; good enough for a static site + simple API
[[vm]]
size = "shared-cpu-1x"
memory = "256mb"
